--liquibase formatted sql

--changeset Abbad:0.1/1

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START 1000;

CREATE TABLE USERS(
    ID   BIGINT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE ROLES(
    ID   BIGINT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL
);

CREATE TABLE USERS_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);


ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_PK PRIMARY KEY (USER_ID,ROLE_ID);
ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

