--liquibase formatted sql

--changeset Abbad:0.1/1

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START 1000;

CREATE TABLE USERS(
    ID   BIGINT PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE ROLES(
    ID   BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE USERS_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);


ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_PK PRIMARY KEY (USER_ID,ROLE_ID);
ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

--changeset Abbad:0.1/2

ALTER TABLE USERS ADD COLUMN FIRST_NAME VARCHAR(255);
ALTER TABLE USERS ADD COLUMN LAST_NAME VARCHAR(255);
ALTER TABLE USERS ADD CONSTRAINT USERNAME_UNIQUE UNIQUE(USERNAME);
